import json

test_list = ['ABO RH', 'Albumin', 'Antibody Screen', 'ACTH', 'AFP', 'Quad Screen', 'Anti Mullerian Hormone Assay', 'Amylase', 'ANA', 'Androstenedione', 'aPTT',  'Antistreptolysin O Titer', 'BNP', 'BMP',  'Cow Milk IgG', 'Egg Mix IgG', 'Corn IgG', 'Oat IgG', 'Peanut IgG', 'Soybean IgG', 'Wheat IgG', 'CBC',
             'Ceruloplasmin', 'CMP', 'Copper', 'Cortisol', 'Creatine Kinase', 'CRP', 'DHEA sulfate', 'D Dimer', 'EBV Early Antigen',  'EBV', 'Drug Screen','ESR', 'Estradiol', 'Ferritin', 'Folate', 'FSH', 'FSH & LH', 'Free T3', 'Free T4', 'HbA1C', 'Hep I Panel', 'Liver Function Panel', 'Hypothyroid Panel', 'IgE', 'Immunoglobulin IgG',  'Iron Panel', 'LDH', 'Lipid Panel', 'LH', 'Lipase', 'Lyme Disease IgG & IgM', 'Microalbumin and Creatinine', 'Magnesium', 'MMR', 'Mono',  'Ova & Parasite', 'Phosphorus', 'Procalcitonin', 'Prolactin', 'Progesterone', 'PSA', 'PTH', 'PT/INR', 'PT/INR and APTT', 'Quant bHCG', 'QuantiFERON TB', 'Renal Function Panel', 'Rubella', 'Rheumatoid Factor', 'Aldosterone', 'Selenium', 'T3 Uptake', 'Testosterone', 'Testosterone, Free & Total',  'Thyroglobulin Ab',  'TPO Ab', 'Thyroid Stimulating Ig', 'T3 Total', 'Total T4', 'Triglyceride', 'TSH', 'UA', 'Urine Alcohol', 'UA with Microscopic', 'Uric Acid',   'Valproic Acid', 'Vitamin B12', 'Vitamin D25',  'Vitamin A', 'Vitamin B1', 'Zinc','HSV 1&2 IGG', 'HSV 1&2 IGM', 'GC CT RNA', 'Hep I Panel', 'Hep A IGM', 'Hep B Core IGM', 'Hep B Sur Ag', 'Hep C Ab','RPR','HIV Ab']

test_dict = {'tests':
['ABO/RH', 'Albumin', 'Antibody Screen', 'Adrenocorticotropic Hormone', 'AFP Tumor Marker', 'Quad Screen', 'Anti-Mullerian Hormone Assay', 'Amylase', 'Antinuclear Antibody Test', 'Androstenedione',  'Activated Partial Thromboplastin Time', 'Antistreptolysin O Titer', 'BNP: B-type Natriuretic Peptide', 'Basic Metabolic Panel', 'Cow Milk IGG', 'Egg Mix(yolk and white) IGG',  'Maize/Corn IGG', 'Oat IGG', 'Peanut IGG', 'Soybean IGG', 'Wheat IGG', 'Complete Blood Count with Auto Diff', 'Ceruloplasmin', 'Comprehensive Metabolic Panel', 'Copper', 'Cortisol', 'Creatine Kinase',   'C-Reactive Protein', 'DHEA-sulfate', 'D-Dimer', 'Epstein-Barr Virus Early Antigen EA', 'EBV Evaluation', 'Drug Screen- 8 drug screening panel', 'Erythrocyte Sedimentation Rate', 'Estradiol', 'Ferritin', 'Folate', 'Follicle-Stimulating Hormone', 'FSH & LH', 'Free T3', 'Free T4', 'Hemoglobin A1C', 'Hepatitis I Panel', 'Hepatic Function Panel', 'Hypothyroid Panel', 'Immunoglobulin IGE', 'Immunoglobulin IGG', 'Iron Panel',  'Lactate Dehydrogenase', 'Lipid Panel', 'Luteinizing Hormone', 'Lipase', 'Lyme Disease Antibody IGG & IGM', 'Microalbumin/Creatinine, Random', 'Magnesium', 'Measles, Mumps & Rubella', 'Mono', 'Ova & Parasite', 'Phosphorus', 'Procalcitonin', 'Prolactin', 'Progesterone', 'Prostatic Specific Antigen, Total', 'Intact PTH', 'Prothrombin Time with INR', 'PT/INR and aPTT', 'Beta hCG, Quantitative', 'QuantiFERON-TB Gold',  'Renal Function Panel', 'Rubella', 'Rheumatoid Factor', 'Aldosterone', 'Selenium', 'T3 Uptake', 'Testosterone', 'Testosterone, Free & Total', 'Thyroglobulin Antibody', 'Thyroid Peroxidase Autoantibody', 'Thyroid Stimulating Immunoglobulin', 'T3 Total', 'Total T4', 'Triglyceride', 'Thyroid Stimulating Hormone', 'Urinalysis, Complete', 'Urine Alcohol', 'Urinalysis with Microscopic', 'Uric Acid', 'Valproic Acid (Depakote)', 'Vitamin B12','Vitamin D-25 Hyd', 'Vitamin A', 'Vitamin B1', 'Zinc',  'Herpes Simplex Virus 1, 2 IgG Type Specific Antibodies', 'HSV 1 & 2 IgM Antibodies', 'Chlamydia & Gonorrhea RNA', 'Hepatitis 1 Panel', 'Hepatitis A IGM', 'Hepatitis B Core IGM', 'Hepatitis B Surface Antigen', 'Hepatitis C Antibody', 'Rapid Plasma Reagin (Syphilis)','HIV Antibody'],

'panels': {"Women's Health Panel": ['CBC', 'CMP', 'UA', 'Lipid Panel', 'HbA1C', 'TSH'],
           "Men's Health Panel": ['CMP', 'CBC', 'UA', 'Lipid panel', 'HbA1C', 'Testosterone', 'PSA'],
           'General Health Panel': ['CMP', 'CBC', 'UA', 'TSH'],
           'Comprehensive Wellness Panel': ['CMP', 'CBC', 'UA', 'LIPID panel', 'HbA1C'],
           'Vitamin Deficiency': ['Vitamin B12', 'Vitamin D25'],
           'Anemia Panel': ['CBC', 'FOLATE', 'Iron panel', 'Vitamin B12', 'Ferritin'],
           'Thyroid Health Panel': ['TSH', 'Free T4'],
           'Heart Health Panel': ['CRP', 'Lipid panel'],
           'Diabetes Management Panel': ['HbA1C', 'CMP', 'LIPID panel', 'Albumin'],
           'Sexually Transmited Disease': ['HIV Ab', 'GC CT RNA', 'RPR', 'Hep C ab', 'HEP b SUR AG'],
           "Women's Hormone Panel": ['Estradiol', 'Testosterone', 'FSH', 'TSH', 'Free T4', 'T3 UPTAKE', 'TPO Ab', 'CMP', 'Lipid Panel', 'Vitamin D25', 'CBC', 'Vitamin B12'],
           'Food Allergy Panel': ['Cow Milk IGG', 'Egg Mix IGG', 'Corn IGG', 'Oat IGG', 'Peanut IGG', 'Soybean IGG', 'Wheat IGG']}}

test_link_list = [159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 152, 172, 173, 174, 175, 176, 177, 178, 154, 179, 155, 180, 181, 182, 183, 184, 185, 186, 187, 156, 188, 189, 190, 191, 192, 193, 194, 195, 196, 158, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 157, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 250, 158, 251, 252, 253, 254, 249, 255]

panel_link_dict = {"Women's Health Panel": 141, "Men's Health Panel": 142, 'General Health Panel': 143, 'Comprehensive Wellness Panel': 144, 'Vitamin Deficiency': 145, 'Anemia Panel': 146, 'Thyroid Health Panel': 147, 'Heart Health Panel': 148, 'Diabetes Management Panel': 149, 'Sexually Transmited Disease': 150, "Women's Hormone Panel": 151, 'Food Allergy Panel': 153}

reference_mask = {'tests': {0: [], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: [], 10: [65], 11: [], 12: [], 13: [], 14: [], 15: [], 16: [], 17: [], 18: [], 19: [], 20: [], 21: [], 22: [], 23: [], 24: [], 25: [], 26: [], 27: [], 28: [], 29: [], 30: [], 31: [30], 32: [], 33: [], 34: [], 35: [], 36: [], 37: [38], 38: [], 39: [], 40: [], 41: [], 42: [96], 43: [], 44: [], 45: [], 46: [], 47: [], 48: [], 49: [], 50: [38], 51: [], 52: [], 53: [], 54: [], 55: [], 56: [], 57: [], 58: [], 59: [], 60: [], 61: [], 62: [], 63: [], 64: [65], 65: [], 66: [], 67: [], 68: [], 69: [55], 70: [], 71: [], 72: [], 73: [], 74: [75], 75: [], 76: [], 77: [], 78: [], 79: [], 80: [], 81: [], 82: [], 83: [85], 84: [], 85: [], 86: [], 87: [], 88: [], 89: [], 90: [], 91: [], 92: [], 93: [], 94: [], 95: [], 96: [], 97: [], 98: [], 99: [], 100: [], 101: [], 102: []}, 
'panels': {"Women's Health Panel": [21, 23, 83, 49, 41, 82], "Men's Health Panel": [23, 21, 83, 49, 41, 74, 62], 'General Health Panel': [23, 21, 83, 82], 'Comprehensive Wellness Panel': [23, 21, 83, 49, 41], 'Vitamin Deficiency': [88, 89], 'Anemia Panel': [21, 36, 47, 88, 35], 'Thyroid Health Panel': [82, 40], 'Heart Health Panel': [27, 49], 'Diabetes Management Panel': [41, 23, 49, 1], 'Sexually Transmited Disease': [102, 95, 101, 100, 99], "Women's Hormone Panel": [34, 74, 37, 82, 40, 73, 77, 23, 49, 89, 21, 88], 'Food Allergy Panel': [14, 15, 16, 17, 18, 19, 20]}}

test_list_str = json.dumps(test_list)
test_dict_str = json.dumps(test_dict['tests'])
test_list_lower = [word.lower() for word in test_list]
test_dict_lower = [word.lower() for word in test_dict['tests']]


