import json
import re


test_list = ['ABO RH', 'Albumin', 'Antibody Screen', 'ACTH', 'AFP', 'Quad Screen', 'Anti Mullerian Hormone Assay', 'Amylase', 'ANA', 'Androstenedione', 'aPTT', 'Antistreptolysin O Titer', 'BNP', 'BMP', 'Custom Allergy Panel', 'Cow Milk IGG', 'Egg Mix IGG', 'Corn IGG', 'Oat IGG', 'Peanut IGG', 'Soybean IGG', 'Wheat IGG', 'CBC', 'Ceruloplasmin', 'CMP', 'Copper', 'Cortisol', 'Creatine Kinase', 'CRP', 'DHEA sulfate', 'D Dimer', 'EBV Early Antigen EA',  'EBV', 'Drug Screen', 'ESR', 'Estradiol', 'Ferritin', 'Folate', 'FSH', 'FSH & LH', 'Free T3', 'Free T4', 'HbA1C', 'Hep I Panel', 'Hepatic Function Panel', 'Hypothyroid Panel', 'Immunoglobulin IGE', 'Immunoglobulin IGG',  'Iron Panel', 'LDH', 'Lipid Panel', 'LH', 'Lipase', 'Lyme Disease IGG & IGM', 'Microalbumin and Creatinine', 'Magnesium', 'MMR', 'Mono', 'Ova & Parasite', 'Phosphorus', 'Procalcitonin', 'Prolactin', 'Progesterone', 'PSA', 'PTH', 'PT INR', 'PT INR and APTT', 'Quant bHCG', 'QuantiFERON TB', 'Renal Function Panel', 'Rubella', 'Rheumatoid Factor', 'Aldosterone', 'Selenium', 'T3 Uptake', 'Testosterone', 'Testosterone, Free & Total',   'Thyroglobulin Antibody', 'TPO antibody', 'Thyroid Stimulating Immunoglobulin', 'T3 Total', 'Total T4', 'Triglyceride', 'TSH', 'Urinalysis', 'Urine Alcohol', 'UA with Microscopic', 'Uric Acid', 'Valproic Acid', 'Vitamin B12', 'Vitamin D25',  'Vitamin A', 'Vitamin B1', 'Zinc','HSV 1&2 IGG', 'HSV 1&2 IGM', 'GC CT RNA', 'Hep 1 Panel', 'Hep A IGM', 'Hep B Core IGM', 'Hep B Sur Ag', 'Hep C Ab','RPR','HIV Ab']

test_dict = {'tests': 
['ABO/RH', 'Albumin', 'Antibody Screen', 'Adrenocorticotropic Hormone', 'AFP Tumor Marker', 'Quad Screen', 'Anti-Mullerian Hormone Assay', 'Amylase', 'ANA- Antinuclear Antibody Test', 'Androstenedione',    'Activated Partial Thromboplastin Time', 'Antistreptolysin O Titer', 'BNP: B-type Natriuretic Peptide', 'Basic Metabolic Panel', 'Custom Allergy Panel', 'Cow Milk IGG', 'Egg Mix(yolk and white) IGG',   'Maize/Corn IGG', 'Oat IGG', 'Peanut IGG', 'Soybean IGG', 'Wheat IGG', 'Complete Blood Count with Auto Diff', 'Ceruloplasmin', 'Comprehensive Metabolic Panel', 'Copper', 'Cortisol', 'Creatine Kinase',   'C-Reactive Protein', 'DHEA-sulfate', 'D-Dimer', 'Epstein-Barr Virus Early Antigen EA', 'EBV Evaluation', 'Drug Screen- Preemployment', 'Erythrocyte Sedimentation Rate', 'Estradiol', 'Ferritin', 'Folate', 'Follicle-Stimulating Hormone', 'FSH & LH', 'Free T3', 'Free T4', 'Hemoglobin A1C', 'Hepatitis I Panel', 'Hepatic Function Panel', 'Hypothyroid Panel', 'Immunoglobulin IGE', 'Immunoglobulin IGG', 'Iron Panel',  'LDH', 'Lipid Panel', 'Luteinizing Hormone', 'Lipase', 'Lyme Disease Antibody IGG & IGM', 'Microalbumin/Creatinine, Random', 'Magnesium', 'Measles, Mumps & Rubella', 'Mono', 'Ova & Parasite', 'Phosphorus',   'Procalcitonin', 'Prolactin', 'Progesterone', 'Prostatic Specific Antigen, Total', 'Intact PTH', 'Prothrombin Time with INR', 'PTINR and APTT', 'Beta hCG, Quantitative', 'QuantiFERON-TB Gold',  'Renal Function Panel', 'Rubella', 'Rheumatoid Factor', 'Aldosterone', 'Selenium', 'T3 Uptake', 'Testosterone', 'Testosterone, Free & Total', 'Thyroglobulin Antibody', 'Thyroid Peroxidase Autoantibody', 'Thyroid Stimulating Immunoglobulin', 'T3 Total', 'Total T4', 'Triglyceride', 'TSH', 'Urinalysis, Complete', 'Urine Alcohol', 'Urinalysis with Microscopic', 'Uric Acid', 'Valproic Acid (Depakote)', 'Vitamin B12','Vitamin D-25 Hyd', 'Vitamin A', 'Vitamin B1', 'Zinc',  'HERPES SIMPLEX VIRUS 1, 2 IGG TYPE SPECIFIC ABS', 'HSV 1 & 2 IGM ABS',  'CHLAMYDIA & GONORRHEA RNA', 'Hepatitis 1 Panel', 'Hepatitis A IGM', 'Hepatitis B Core IGM', 'Hepatitis B Surface Antigen', 'Hepatitis C Antibody','Rapid Plasma Reagin (Syphilis)','HIV Antibody'],  

'panels': {"Women's Health Panel": 'CBC, CMP, UA, Lipid Panel, HbA1C, TSH', 
           "Men's Health Panel": 'CMP, CBC, UA, Lipid panel, HbA1C, Testosterone, PSA', 
           'General Health Panel': 'CMP, CBC, UA, TSH',    
           'Comprehensive Wellness Panel': 'CMP, CBC, UA, LIPID panel, HbA1C', 
           'Vitamin Deficiency': 'Vitamin B12, Vitamin D25', 'Anemia Panel': 'CBC, FOLATE, Iron panel, Vitamin B12, Ferritin',  
           'Thyroid Health Panel': 'TSH, Free T4', 
           'Heart Health Panel': 'CRP, Lipid panel',   
           'Diabetes Management Panel': 'HbA1C, CMP, LIPID panel, Albumin', 
           'Sexually Transmited Disease': 'HIV Ab, GC CT RNA, RPR, Hep C ab, HEP b SUR AG', 
           "Women's Hormone Panel": 'Estradiol, Testosterone, FSH, TSH, Free T4, T3 UPTAKE, TPO antibody, CMP, Lipid Panel, Vitamin D25, CBC, Vitamin B12'}}

reference_mask = {'tests': {0: [], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: [], 10: [66], 11: [], 12: [], 13: [], 14: [], 15: [14], 16: [14], 17: [14], 18: [14], 19: [14], 20: [14], 21: [14], 22: [], 23: [], 24: [], 25: [], 26: [], 27: [], 28: [], 29: [], 30: [], 31: [], 32: [31], 33: [], 34: [], 35: [], 36: [], 37: [], 38: [39], 39: [], 40: [], 41: [], 42: [], 43: [], 44: [], 45: [], 46: [], 47: [], 48: [], 49: [], 50: [], 51: [39], 52: [], 53: [], 54: [], 55: [], 56: [], 57: [], 58: [], 59: [], 60: [], 61: [], 62: [], 63: [], 64: [], 65: [66], 66: [], 67: [], 68: [], 69: [], 70: [56], 71: [], 72: [], 73: [], 74: [], 75: [76], 76: [], 77: [], 78: [], 79: [], 80: [], 81: [], 82: [], 83: [], 84: [86], 85: [], 86: [], 87: [], 88: [], 89: [], 90: [], 91: [], 92: [], 93: [], 94: [], 95: [], 96: [], 97: [], 98: [], 99: [], 100: [], 101: [], 102: [], 103: []}, 
                  'panels': {"Women's Health Panel": [22, 24, 84, 50, 42, 83], "Men's Health Panel": [24, 22, 84, 50, 42, 75, 63], 'General Health Panel': [24, 22, 84, 83], 'Comprehensive Wellness Panel': [24, 22, 84, 50, 42], 'Vitamin Deficiency': [89, 90], 'Anemia Panel': [22, 37, 48, 89, 36], 'Thyroid Health Panel': [83, 41], 'Heart Health Panel': [28, 50], 'Diabetes Management Panel': [42, 24, 50, 1], 'Sexually Transmited Disease': [103, 96, 102, 101, 100], "Women's Hormone Panel": [35, 75, 38, 41, 81, 74, 78, 24, 50, 90, 22, 89]}}

test_list_str = json.dumps(test_list)
test_dict_str = json.dumps(test_dict['tests'])
test_list_lower = [word.lower() for word in test_list]
test_dict_lower = [word.lower() for word in test_dict['tests']]


